name: Deploy Backend to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'apps/server/**'
      - 'package.json'
      - 'bun.lock'
      - 'vercel.json'
  pull_request:
    branches: [main]
    paths:
      - 'apps/server/**'
      - 'package.json'
      - 'bun.lock'
      - 'vercel.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma client
        run: |
          cd apps/server
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la
          echo "Checking if prisma directory exists:"
          ls -la prisma/ || echo "Prisma directory not found"
          echo "Running Prisma generate..."
          bun run db:generate
          echo "Checking if client was generated:"
          ls -la prisma/generated/ || echo "Generated directory not found"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run type checking
        run: bun run type-check

      - name: Run linting
        run: bun run lint

      - name: Run tests
        run: bun run test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
